In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df = pd.get_dummies(df,columns=['Geography'])

In [4]:
df=df.drop(['CustomerId','Surname'],axis=1)

In [5]:
x=df.drop('Exited',axis=1)
y=df['Exited']

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout

model = Sequential([
    Input(shape=(x_train.shape[1],)),
    Dense(64,activation='relu'),
    Dropout(0.5),
    Dense(32,activation='relu'),
    Dropout(0.5),
    Dense(1,activation='sigmoid')])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [9]:
history = model.fit(x_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7045 - loss: 0.6019 - val_accuracy: 0.8025 - val_loss: 0.4341
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7967 - loss: 0.4868 - val_accuracy: 0.8294 - val_loss: 0.4160
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4716 - val_accuracy: 0.8375 - val_loss: 0.4090
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8212 - loss: 0.4421 - val_accuracy: 0.8444 - val_loss: 0.4024
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8064 - loss: 0.4637 - val_accuracy: 0.8425 - val_loss: 0.3944
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8152 - loss: 0.4309 - val_accuracy: 0.8450 - val_loss: 0.3860
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8171 - loss: 0.4326 - val_accuracy: 0.8487 - val_loss: 0.3768
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8250 - loss: 0.4131 - val_accuracy: 0.8475 - val_loss: 0.3697
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8339 - loss: 0.4029 - val_accuracy: 0.8531 - val_loss: 0.3641
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8411 - loss: 0.3884 - val_accuracy: 0.8494 - val_loss: 0.3595
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8373 - loss: 0.3778 - val_accuracy: 0.8525 - val_loss: 0.3577
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8427 - loss: 0.3835 - val_accuracy: 0.8569 - val_loss: 0.3550
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8444 - loss: 0.3900 - val_accuracy: 0.8594 - val_loss: 0.3525
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8408 - loss: 0.3812 - val_accuracy: 0.8575 - val_loss: 0.3519
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8402 - loss: 0.3816 - val_accuracy: 0.8587 - val_loss: 0.3504
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8508 - loss: 0.3627 - val_accuracy: 0.8562 - val_loss: 0.3529
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8432 - loss: 0.3755 - val_accuracy: 0.8531 - val_loss: 0.3508
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8485 - loss: 0.3685 - val_accuracy: 0.8575 - val_loss: 0.3491
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8427 - loss: 0.3796 - val_accuracy: 0.8587 - val_loss: 0.3487
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8517 - loss: 0.3651 - val_accuracy: 0.8562 - val_loss: 0.3487
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8535 - loss: 0.3696 - val_accuracy: 0.8587 - val_loss: 0.3464
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8494 - loss: 0.3710 - val_accuracy: 0.8556 - val_loss: 0.3471
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8469 - loss: 0.3661 - val_accuracy: 0.8594 - val_loss: 0.3469
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8587 - loss: 0.3452 - val_accuracy: 0.8606 - val_loss: 0.3447
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8526 - loss: 0.3612 - val_accuracy: 0.8569 - val_loss: 0.3469
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8572 - loss: 0.3540 - val_accuracy: 0.8612 - val_loss: 0.3442
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8562 - loss: 0.3593 - val_accuracy: 0.8612 - val_loss: 0.3431
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8652 - loss: 0.3410 - val_accuracy: 0.8625 - val_loss: 0.3418
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8535 - loss: 0.3552 - val_accuracy: 0.8631 - val_loss: 0.3425
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8447 - loss: 0.3703 - val_accuracy: 0.8587 - val_loss: 0.3441
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8571 - loss: 0.3505 - val_accuracy: 0.8637 - val_loss: 0.3413
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8585 - loss: 0.3492 - val_accuracy: 0.8612 - val_loss: 0.3429
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8609 - loss: 0.3463 - val_accuracy: 0.8631 - val_loss: 0.3431
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8509 - loss: 0.3523 - val_accuracy: 0.8631 - val_loss: 0.3431
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8552 - loss: 0.3537 - val_accuracy: 0.8612 - val_loss: 0.3404
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8579 - loss: 0.3471 - val_accuracy: 0.8606 - val_loss: 0.3408
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8484 - loss: 0.3597 - val_accuracy: 0.8612 - val_loss: 0.3399
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8643 - loss: 0.3443 - val_accuracy: 0.8612 - val_loss: 0.3403
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3467 - val_accuracy: 0.8631 - val_loss: 0.3388
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8604 - loss: 0.3425 - val_accuracy: 0.8594 - val_loss: 0.3401
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8635 - loss: 0.3608 - val_accuracy: 0.8606 - val_loss: 0.3405
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8499 - loss: 0.3671 - val_accuracy: 0.8575 - val_loss: 0.3406
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3380 - val_accuracy: 0.8587 - val_loss: 0.3414
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3431 - val_accuracy: 0.8612 - val_loss: 0.3415
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8640 - loss: 0.3502 - val_accuracy: 0.8631 - val_loss: 0.3407
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8657 - loss: 0.3432 - val_accuracy: 0.8612 - val_loss: 0.3413
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8616 - loss: 0.3481 - val_accuracy: 0.8587 - val_loss: 0.3414
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3464 - val_accuracy: 0.8575 - val_loss: 0.3409
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8547 - loss: 0.3532 - val_accuracy: 0.8594 - val_loss: 0.3424
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8599 - loss: 0.3479 - val_accuracy: 0.8600 - val_loss: 0.3418

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = (model.predict(x_test)>0.5).astype("int32")
accuracy = accuracy_score(y_test,y_pred) 
conf_matrix = confusion_matrix(y_test,y_pred)

print("Accuracy: ",accuracy)
print("Confusion matrix: ")
print(conf_matrix)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy:  0.8615
Confusion matrix:
[[1549   58]
 [ 219  174]]

In [12]:
df

,RowNumber,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,1,619,0,42,2,0.00,1,1,1,101348.88,1,True,False,False
1,2,608,0,41,1,83807.86,1,0,1,112542.58,0,False,False,True
2,3,502,0,42,8,159660.80,3,1,0,113931.57,1,True,False,False
3,4,699,0,39,1,0.00,2,0,0,93826.63,0,True,False,False
4,5,850,0,43,2,125510.82,1,1,1,79084.10,0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,771,1,39,5,0.00,2,1,0,96270.64,0,True,False,False
9996,9997,516,1,35,10,57369.61,1,1,1,101699.77,0,True,False,False
9997,9998,709,0,36,7,0.00,1,0,1,42085.58,1,True,False,False
9998,9999,772,1,42,3,75075.31,2,1,0,92888.52,1,False,True,False
9999,10000,792,0,28,4,130142.79,1,1,0,38190.78,0,True,False,False